manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sitrucy
      url-base: https://github.com/SitrucyCodes
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: keyboard
      remote: sitrucy
      revision: main
  self:
    path: config
